version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/project/static
      - media_volume:/home/project/media
    depends_on:
      - gunicorn

  gunicorn:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application" --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/project/static
      - media_volume:/home/project/media
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
